### ISSUE TITLE
The Reason returned by :odbc.connect on error is not always a string

### ISSUE THREAD

**Issue by sam-pd** [pepsico-ecommerce/snowflex#36]
:odbc.connect returns {:error, Reason}, but Reason isn't guaranteed to be something that is stringable.  A very common example would be hitting the file/process limit on OSX, which throws {:emfile, [...]}.  This leads to the case statement throwing a (`(Protocol.UndefinedError) protocol String.Chars not implemented for...`)  which is a bit of a red herring.

Tossing an inspect on the log line [here](https://github.com/pepsico-ecommerce/snowflex/blob/1b10a1764038c62df102a1f7c5fb1fc65b0dc8c6/lib/snowflex/worker.ex#L85) would make it easier to debug the underlying issue, especially the first time you come across it.

**Comment by Ch4s3** [comment]
@sam-pd  I'd be happy to review and merge a PR for this.
