### ISSUE TITLE
interpolation error

### ISSUE THREAD

**Issue by sescobb27** [pepsico-ecommerce/snowflex#41]
Hi there, i was trying to follow your docs on how to execute queries with external data via `?` placeholders using delete queries, but i'm getting a weird error which i'm not able to identify the reason, maybe you are aware of it, or is there a limitation on the lib side.

so, this one works as expected

```elixir
iex> JobApi.SnowflakeConnection.execute("DELETE FROM all_events_v3 WHERE (account_id='15094')")
{:updated, 1}
```

but when using placeholders it returns an error
```elixir
iex> JobApi.SnowflakeConnection.execute("DELETE FROM all_events_v3 WHERE (account_id=?)", [Snowflex.string_param("15094")])
{:error, 'No SQL-driver information available.'}
```

i'm using the latest version

**Comment by notactuallytreyanastasio** [comment]
@sescobb27 this is really just a lack of good documentation.

Placeholders are interpreted using `:NUMBER`, and interpolated in order with 1-indexing.

So, to fix your second query you want:

```elixir
JobApi.SnowflakeConnection.execute("DELETE FROM all_events_v3 WHERE (account_id=:1)", [Snowflex.string_param("15094")])
```

If you would like to improve the documentation around this, pull requests are welcome. I'll make a note that we should improve this but don't know when we will get to it with some other priorities coming for a new major release.

**Comment by hexchung** [comment]
Hi, opening this up again because even with the suggested interpolation pattern above `:NUMBER`, the driver is still not binding the variable. Is this pattern still applicable?

**Comment by sescobb27** [comment]
I never tried to be honest, we are just sanitizing everything and doing interpolation and that worked
